baseurl: "https://ulrik-vj.github.io/portfolio/"
title: "Ulrik's portfolio"
languageCode: "en-UK"
theme: ["no-js-hugo-theme"]
enableEmoji: true
publishDir: "public"
pagination.pagerSize: 4
capitalizeListTitles: false
params:
  themeStyleSwitcher: true
  themeStyle: "dark.css"
  footerText: "Ulriks webpage @2025"
  summaryLength: 10
markup:
  highlight:
    codeFences: true
    noClasses: false
  tableOfContents:
    startLevel: 1
    endLevel: 6

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: -120
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: -110
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: -100
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: -90 
   
