name = "No-JS Hugo Theme"
license = "MIT (except for stock photos)"
description = "A minimal and responsive Hugo theme that does not require the client to enable JavaScript."
tags = []
features = []
min_version = "0.38"

[author]
  name = "Steven Engler"
