name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo

      - name: Check for Changes
        run: |
          cd ${GITHUB_WORKSPACE}/built-site
          if git diff --quiet; then
            echo "No changes to deploy."
            exit 0
          fi

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          git config user.name 'ulrik-vj'
          git commit -m 'Updated site'
          git push
